[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  REACT_APP_API_URL = "https://rnc-malaysia-api.onrender.com/api"

# Production environment
[context.production.environment]
  REACT_APP_API_URL = "https://rnc-malaysia-api.onrender.com/api"

# Deploy preview environment
[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://rnc-malaysia-api.onrender.com/api"

# Branch deploy environment
[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://rnc-malaysia-api.onrender.com/api"

# Handle client-side routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://rnc-malaysia-api.onrender.com https://api.rncmalaysia.org;"
  NODE_VERSION = "16"
